version: '3'
services:
  #PHP service
  app:
    image: simple-local:2.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: local_simple2_app
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    working_dir: /var/www
    volumes:
      - ./../../:/var/www
      - ./../../setup/local/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - local_simple2-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: local_simple2_server
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    volumes:
      - ./../../:/var/www
      - ./../../setup/local/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${APP_PORT}:80"
      - "443:443"
    networks:
      - local_simple2-network

  # Bdd Service
  mysql_service:
    image: "mysql:5.7"
    container_name: local_simple2_db
    command: ["--sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    restart: unless-stopped
    networks:
      - local_simple2-network

  # Elasticsearch Service
  elastic:
    image: "elasticsearch:5.6"
    container_name: local_simple2_elastic
    environment:
      - discovery.type=single-node
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
    networks:
      - local_simple2-network
    depends_on:
      - mysql_service

#Volumes
volumes:
  mysql_data:
  elastic_data:

#Docker Networks
networks:
  local_simple2-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16